# Generated by Django 4.2.30 on 2026-07-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('domaine', models.CharField(max_length=200, verbose_name='Domaine souhaité')),
                ('niveau', models.CharField(choices=[('DEBUTANT', 'Débutant'), ('INTERMEDIAIRE', 'Intermédiaire'), ('AVANCE', 'Avancé'), ('PROFESSIONNEL', 'Professionnel')], default='DEBUTANT', max_length=20, verbose_name='Niveau')),
                ('message', models.TextField(verbose_name='Message / Précisions')),
                ('status', models.CharField(choices=[('RECU', 'Reçu'), ('EN_TRAITEMENT', 'En traitement'), ('TRAITE', 'Traité'), ('REJETE', 'Rejeté')], default='RECU', max_length=20, verbose_name='Statut')),
                ('admin_notes', models.TextField(blank=True, help_text="Notes réservées à l'administration.", verbose_name='Notes internes')),
            ],
            options={
                'verbose_name': 'Demande de formation',
                'verbose_name_plural': 'Demandes de formation',
                'ordering': ['-created_at'],
            },
        ),
    ]
