# Generated by Django 6.0.6 on 2026-07-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(default='CM', help_text='Code ISO 2 lettres (ex: CM, CI, FR, SN)', max_length=2, verbose_name='Pays'),
        ),
    ]
