# Generated by Django 4.2.30 on 2026-07-05 09:49

import apps.core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, help_text="Nom de l'icône (ex: solar-panel, zap, tool)", max_length=50, verbose_name='Icône')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Chapitre',
                'verbose_name_plural': 'Chapitres',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=280, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('objectives', models.TextField(blank=True, help_text='Un objectif par ligne.', verbose_name='Objectifs')),
                ('prerequisites', models.TextField(blank=True, help_text='Un prérequis par ligne.', verbose_name='Prérequis')),
                ('image', models.ImageField(upload_to=apps.core.utils.UploadToPathAndRename('formations/images'), validators=[apps.core.utils.validate_image_file], verbose_name='Image de couverture')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Prix (FCFA)')),
                ('is_free', models.BooleanField(default=False, verbose_name='Formation gratuite')),
                ('level', models.CharField(choices=[('DEBUTANT', 'Débutant'), ('INTERMEDIAIRE', 'Intermédiaire'), ('AVANCE', 'Avancé')], default='DEBUTANT', max_length=20, verbose_name='Niveau')),
                ('duration_hours', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Durée (heures)')),
                ('status', models.CharField(choices=[('PUBLIE', 'Publié'), ('BROUILLON', 'Brouillon'), ('ARCHIVE', 'Archivé')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mise en avant')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formations', to='formations.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('video_file', models.FileField(blank=True, null=True, upload_to=apps.core.utils.UploadToPathAndRename('formations/videos'), validators=[apps.core.utils.validate_video_file], verbose_name='Fichier vidéo')),
                ('video_url', models.URLField(blank=True, help_text='URL YouTube ou autre (alternative au fichier)', verbose_name='URL vidéo externe')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Durée (minutes)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_preview', models.BooleanField(default=False, help_text='Si coché, cette vidéo est visible sans paiement.', verbose_name='Accessible en aperçu')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='formations.chapitre', verbose_name='Chapitre')),
            ],
            options={
                'verbose_name': 'Vidéo',
                'verbose_name_plural': 'Vidéos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('file', models.FileField(upload_to=apps.core.utils.UploadToPathAndRename('formations/pdfs'), validators=[apps.core.utils.validate_pdf_file], verbose_name='Fichier PDF')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='formations.chapitre', verbose_name='Chapitre')),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='formations.formation', verbose_name='Formation')),
            ],
            options={
                'verbose_name': 'PDF',
                'verbose_name_plural': 'PDFs',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='chapitre',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='formations.formation', verbose_name='Formation'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_active', models.BooleanField(default=True, verbose_name='Accès actif')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Inscrit le')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='formations.formation', verbose_name='Formation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'unique_together': {('user', 'formation')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='chapitre',
            unique_together={('formation', 'order')},
        ),
    ]
