# Generated by Django 6.0.6 on 2026-07-17 09:30

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='intro_video',
            field=models.FileField(blank=True, help_text='Vidéo de présentation visible par tous (optionnelle).', null=True, upload_to=apps.core.utils.UploadToPathAndRename('formations/intros'), validators=[apps.core.utils.validate_video_file], verbose_name="Vidéo d'introduction"),
        ),
        migrations.AddField(
            model_name='formation',
            name='intro_video_url',
            field=models.URLField(blank=True, help_text='Alternative YouTube/Vimeo (si pas de fichier vidéo).', verbose_name="URL vidéo d'introduction"),
        ),
        migrations.AddField(
            model_name='formation',
            name='zip_file',
            field=models.FileField(blank=True, help_text='Contenu principal de la formation au format ZIP (max 500 Mo).', null=True, upload_to=apps.core.utils.UploadToPathAndRename('formations/zips'), validators=[apps.core.utils.validate_zip_file], verbose_name='Fichier ZIP de la formation'),
        ),
    ]
