# Generated by Django 4.2.30 on 2026-07-05 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boutique', '0001_initial'),
        ('formations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant (FCFA)')),
                ('status', models.CharField(choices=[('INITIE', 'Initié'), ('EN_ATTENTE', 'En attente'), ('SUCCES', 'Succès'), ('ECHOUE', 'Échoué'), ('ANNULE', 'Annulé'), ('REMBOURSE', 'Remboursé')], default='INITIE', max_length=20, verbose_name='Statut')),
                ('provider', models.CharField(choices=[('MTN', 'MTN MoMo'), ('ORANGE', 'Orange Money'), ('PAYPAL', 'PayPal')], max_length=20, verbose_name='Méthode de paiement')),
                ('camerpay_reference', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Référence CAMERPAY')),
                ('camerpay_payment_url', models.URLField(blank=True, verbose_name='URL de paiement CAMERPAY')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Payé le')),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='formations.formation', verbose_name='Formation')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='boutique.order', verbose_name='Commande')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
    ]
