# Generated by Django 6.0.6 on 2026-07-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cinetpay_payment_url',
            field=models.URLField(blank=True, verbose_name='URL de paiement CinetPay'),
        ),
        migrations.AddField(
            model_name='payment',
            name='cinetpay_transaction_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Transaction ID CinetPay'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('MTN', 'MTN MoMo'), ('ORANGE', 'Orange Money'), ('CARTE', 'Carte Bancaire'), ('PAYPAL', 'PayPal')], max_length=20, verbose_name='Méthode de paiement'),
        ),
    ]
