# Generated by Django 4.2.30 on 2026-07-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0002_payment_cinetpay_payment_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='monetbil_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Payment ID Monetbil'),
        ),
        migrations.AddField(
            model_name='payment',
            name='monetbil_payment_url',
            field=models.URLField(blank=True, verbose_name='URL de paiement Monetbil'),
        ),
    ]
