# Generated by Django 4.2.30 on 2026-08-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0003_payment_monetbil_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='camerpay_payment_url',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='camerpay_reference',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='cinetpay_payment_url',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='cinetpay_transaction_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='monetbil_payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='monetbil_payment_url',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_url',
            field=models.URLField(blank=True, verbose_name='URL de paiement'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID de Transaction'),
        ),
    ]
