# Generated by Django 4.2.30 on 2026-09-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0004_remove_payment_camerpay_payment_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='monetbil_payment_id',
            field=models.CharField(blank=True, default='', help_text='ID de transaction MonetBil (reçu via webhook)', max_length=255, verbose_name='MonetBil Payment ID'),
        ),
        migrations.AddField(
            model_name='payment',
            name='pawapay_deposit_id',
            field=models.CharField(blank=True, default='', help_text='ID de dépôt PawaPay (reçu via API/webhook)', max_length=255, verbose_name='PawaPay Deposit ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_url',
            field=models.URLField(blank=True, verbose_name='URL de paiement (MonetBil/PawaPay)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('MTN', 'MTN MoMo'), ('ORANGE', 'Orange Money'), ('EU', 'Express Union'), ('PAWAPAY', 'PawaPay Multi-pays')], default='MTN', max_length=20, verbose_name='Méthode de paiement'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Notre référence interne (payment_ref envoyé à MonetBil/PawaPay)', max_length=255, null=True, unique=True, verbose_name='Référence de paiement'),
        ),
    ]
